-- PostgreSQL schema for Patient Check-In
-- Enums use TEXT columns with CHECK constraints

CREATE TABLE IF NOT EXISTS external_source (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           TEXT NOT NULL UNIQUE,
    name           TEXT NOT NULL,
    connector_type TEXT NOT NULL,
    enabled        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS agenda (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS external_agenda (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id          INTEGER NOT NULL REFERENCES agenda (id),
    external_source_id INTEGER NOT NULL REFERENCES external_source (id),
    external_reference TEXT,
    source_name        TEXT,
    UNIQUE (external_source_id, external_reference)
);

CREATE TABLE IF NOT EXISTS ticket_master (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS queue (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status           TEXT NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    policy           TEXT NOT NULL CHECK (policy IN ('BY_ARRIVAL', 'BY_APPOINTMENT')),
    ticket_master_id INTEGER NOT NULL REFERENCES ticket_master (id)
);

-- Links queues and agendas
CREATE TABLE IF NOT EXISTS queue_agenda (
    queue_id  INTEGER NOT NULL REFERENCES queue (id),
    agenda_id INTEGER NOT NULL REFERENCES agenda (id),
    PRIMARY KEY (queue_id, agenda_id)
);

-- Appointments imported from external sources
CREATE TABLE IF NOT EXISTS appointment (
    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduled_at                  TIMESTAMP NOT NULL,
    patient_identifier_type       TEXT NOT NULL,
    patient_identifier_value      TEXT NOT NULL,
    external_agenda_id            INTEGER NOT NULL REFERENCES external_agenda (id),
    external_patient_reference    TEXT,
    external_appointment_reference TEXT
);

-- Prevent duplicate appointments when an external reference is available
CREATE UNIQUE INDEX IF NOT EXISTS appointment_source_reference_key
    ON appointment (external_agenda_id, external_appointment_reference)
    WHERE external_appointment_reference IS NOT NULL;

-- One daily presence for each day and patient identifier
CREATE TABLE IF NOT EXISTS daily_presence (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operational_day          DATE NOT NULL,
    patient_identifier_type  TEXT NOT NULL,
    patient_identifier_value TEXT NOT NULL,
    public_call_code         TEXT NOT NULL,
    ticket_master_id         INTEGER NOT NULL REFERENCES ticket_master (id),
    UNIQUE (operational_day, patient_identifier_type, patient_identifier_value)
);

-- Access to one service, initially in WAITING state
CREATE TABLE IF NOT EXISTS service_access (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_presence_id INTEGER NOT NULL REFERENCES daily_presence (id),
    agenda_id         INTEGER NOT NULL REFERENCES agenda (id),
    appointment_id    INTEGER REFERENCES appointment (id),
    state             TEXT NOT NULL DEFAULT 'WAITING'
                          CHECK (state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED'))
);

-- Prevent duplicate accesses for the same presence and appointment
CREATE UNIQUE INDEX IF NOT EXISTS service_access_presence_appointment_key
    ON service_access (daily_presence_id, appointment_id)
    WHERE appointment_id IS NOT NULL;

-- Daily counter used to generate public call codes
CREATE TABLE IF NOT EXISTS ticket_sequence (
    ticket_master_id INTEGER NOT NULL REFERENCES ticket_master (id),
    operational_day  DATE NOT NULL,
    last_number      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ticket_master_id, operational_day)
);
-- Append-only history of successful ServiceAccess transitions.
-- previous_state is NULL for the initial WAITING creation record.
CREATE TABLE IF NOT EXISTS service_access_transition (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_access_id INTEGER NOT NULL REFERENCES service_access (id),
    previous_state    TEXT
                          CHECK (previous_state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED')),
    resulting_state   TEXT NOT NULL
                          CHECK (resulting_state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED')),
    occurred_at       TIMESTAMP NOT NULL DEFAULT now()
);

-- Lookups by ServiceAccess, and ordering of recent/latest calls by time
CREATE INDEX IF NOT EXISTS service_access_transition_access_key
    ON service_access_transition (service_access_id);
CREATE INDEX IF NOT EXISTS service_access_transition_order_key
    ON service_access_transition (occurred_at DESC, id DESC);

-- Recursive location topology: tree or forest, no fixed levels
CREATE TABLE IF NOT EXISTS location_node (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER REFERENCES location_node (id),
    label     TEXT NOT NULL
);

-- Check-in point, belongs to exactly one LocationNode
CREATE TABLE IF NOT EXISTS totem (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference TEXT NOT NULL UNIQUE,
    location_node_id   INTEGER NOT NULL REFERENCES location_node (id)
);

-- Operational Room, with a unique external reference and a required label
CREATE TABLE IF NOT EXISTS room (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_reference   TEXT NOT NULL UNIQUE,
    label            TEXT NOT NULL,
    location_node_id INTEGER NOT NULL REFERENCES location_node (id)
);

-- At most one workstation per Room, enforced by UNIQUE(room_id)
CREATE TABLE IF NOT EXISTS room_workstation (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL UNIQUE REFERENCES room (id)
);

-- Zero or one monitor per Room, enforced by UNIQUE(room_id)
CREATE TABLE IF NOT EXISTS room_monitor (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL UNIQUE REFERENCES room (id)
);

-- Waiting-room display, associated with one or more LocationNodes (its scope)
CREATE TABLE IF NOT EXISTS waiting_room_monitor (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL
);

-- Scope nodes for a waiting-room display
CREATE TABLE IF NOT EXISTS waiting_room_monitor_scope (
    waiting_room_monitor_id INTEGER NOT NULL REFERENCES waiting_room_monitor (id),
    location_node_id        INTEGER NOT NULL REFERENCES location_node (id),
    PRIMARY KEY (waiting_room_monitor_id, location_node_id)
);

-- Check-in origin: the originating Totem, when supplied at check-in
ALTER TABLE daily_presence ADD COLUMN IF NOT EXISTS totem_id
    INTEGER REFERENCES totem (id);

-- The call-time Room, persisted on a successful call and reused by admission
ALTER TABLE service_access ADD COLUMN IF NOT EXISTS room_id
    INTEGER REFERENCES room (id);
