-- PostgreSQL schema for Patient Check-In
-- Enums use TEXT columns with CHECK constraints

CREATE TABLE IF NOT EXISTS external_source (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           TEXT NOT NULL UNIQUE,
    name           TEXT NOT NULL,
    connector_type TEXT NOT NULL,
    enabled        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS agenda (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS external_agenda (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id          INTEGER NOT NULL REFERENCES agenda (id),
    external_source_id INTEGER NOT NULL REFERENCES external_source (id),
    external_reference TEXT,
    source_name        TEXT,
    UNIQUE (external_source_id, external_reference)
);

CREATE TABLE IF NOT EXISTS ticket_master (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS queue (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status           TEXT NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    policy           TEXT NOT NULL CHECK (policy IN ('BY_ARRIVAL', 'BY_APPOINTMENT')),
    ticket_master_id INTEGER NOT NULL REFERENCES ticket_master (id)
);

-- Links queues and agendas
CREATE TABLE IF NOT EXISTS queue_agenda (
    queue_id  INTEGER NOT NULL REFERENCES queue (id),
    agenda_id INTEGER NOT NULL REFERENCES agenda (id),
    PRIMARY KEY (queue_id, agenda_id)
);

-- Appointments imported from external sources
CREATE TABLE IF NOT EXISTS appointment (
    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduled_at                  TIMESTAMP NOT NULL,
    patient_identifier_type       TEXT NOT NULL,
    patient_identifier_value      TEXT NOT NULL,
    external_agenda_id            INTEGER NOT NULL REFERENCES external_agenda (id),
    external_patient_reference    TEXT,
    external_appointment_reference TEXT
);

-- Prevent duplicate appointments when an external reference is available
CREATE UNIQUE INDEX IF NOT EXISTS appointment_source_reference_key
    ON appointment (external_agenda_id, external_appointment_reference)
    WHERE external_appointment_reference IS NOT NULL;

-- One daily presence for each day and patient identifier
CREATE TABLE IF NOT EXISTS daily_presence (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operational_day          DATE NOT NULL,
    patient_identifier_type  TEXT NOT NULL,
    patient_identifier_value TEXT NOT NULL,
    public_call_code         TEXT NOT NULL,
    ticket_master_id         INTEGER NOT NULL REFERENCES ticket_master (id),
    UNIQUE (operational_day, patient_identifier_type, patient_identifier_value)
);

-- Access to one service, initially in WAITING state
CREATE TABLE IF NOT EXISTS service_access (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_presence_id INTEGER NOT NULL REFERENCES daily_presence (id),
    agenda_id         INTEGER NOT NULL REFERENCES agenda (id),
    appointment_id    INTEGER REFERENCES appointment (id),
    state             TEXT NOT NULL DEFAULT 'WAITING'
                          CHECK (state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED'))
);

-- Prevent duplicate accesses for the same presence and appointment
CREATE UNIQUE INDEX IF NOT EXISTS service_access_presence_appointment_key
    ON service_access (daily_presence_id, appointment_id)
    WHERE appointment_id IS NOT NULL;

-- Daily counter used to generate public call codes
CREATE TABLE IF NOT EXISTS ticket_sequence (
    ticket_master_id INTEGER NOT NULL REFERENCES ticket_master (id),
    operational_day  DATE NOT NULL,
    last_number      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ticket_master_id, operational_day)
);
