"""Create the initial AZFlow database schema.

Revision ID: 6d3c09e02018
Revises:
"""

from __future__ import annotations

from alembic import op

revision = "6d3c09e02018"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the initial AZFlow schema."""
    op.execute(
        "-- PostgreSQL schema for Patient Check-In\n-- Enums use TEXT columns with CHECK constraints\n\nCREATE TABLE IF NOT EXISTS external_source (\n    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    code           TEXT NOT NULL UNIQUE,\n    name           TEXT NOT NULL,\n    connector_type TEXT NOT NULL,\n    enabled        BOOLEAN NOT NULL DEFAULT TRUE\n);\n\nCREATE TABLE IF NOT EXISTS agenda (\n    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    name TEXT NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS external_agenda (\n    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    agenda_id          INTEGER NOT NULL REFERENCES agenda (id),\n    external_source_id INTEGER NOT NULL REFERENCES external_source (id),\n    external_reference TEXT,\n    source_name        TEXT,\n    UNIQUE (external_source_id, external_reference)\n);\n\nCREATE TABLE IF NOT EXISTS ticket_master (\n    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    prefix TEXT NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS queue (\n    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    status           TEXT NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),\n    policy           TEXT NOT NULL CHECK (policy IN ('BY_ARRIVAL', 'BY_APPOINTMENT')),\n    ticket_master_id INTEGER NOT NULL REFERENCES ticket_master (id)\n);\n\n-- Links queues and agendas\nCREATE TABLE IF NOT EXISTS queue_agenda (\n    queue_id  INTEGER NOT NULL REFERENCES queue (id),\n    agenda_id INTEGER NOT NULL REFERENCES agenda (id),\n    PRIMARY KEY (queue_id, agenda_id)\n);\n\n-- Appointments imported from external sources\nCREATE TABLE IF NOT EXISTS appointment (\n    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    scheduled_at                  TIMESTAMP NOT NULL,\n    patient_identifier_type       TEXT NOT NULL,\n    patient_identifier_value      TEXT NOT NULL,\n    external_agenda_id            INTEGER NOT NULL REFERENCES external_agenda (id),\n    external_patient_reference    TEXT,\n    external_appointment_reference TEXT\n);\n\n-- Prevent duplicate appointments when an external reference is available\nCREATE UNIQUE INDEX IF NOT EXISTS appointment_source_reference_key\n    ON appointment (external_agenda_id, external_appointment_reference)\n    WHERE external_appointment_reference IS NOT NULL;\n\n-- One daily presence for each day and patient identifier\nCREATE TABLE IF NOT EXISTS daily_presence (\n    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    operational_day          DATE NOT NULL,\n    patient_identifier_type  TEXT NOT NULL,\n    patient_identifier_value TEXT NOT NULL,\n    public_call_code         TEXT NOT NULL,\n    ticket_master_id         INTEGER NOT NULL REFERENCES ticket_master (id),\n    UNIQUE (operational_day, patient_identifier_type, patient_identifier_value)\n);\n\n-- Access to one service, initially in WAITING state\nCREATE TABLE IF NOT EXISTS service_access (\n    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    daily_presence_id INTEGER NOT NULL REFERENCES daily_presence (id),\n    agenda_id         INTEGER NOT NULL REFERENCES agenda (id),\n    appointment_id    INTEGER REFERENCES appointment (id),\n    state             TEXT NOT NULL DEFAULT 'WAITING'\n                          CHECK (state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED'))\n);\n\n-- Prevent duplicate accesses for the same presence and appointment\nCREATE UNIQUE INDEX IF NOT EXISTS service_access_presence_appointment_key\n    ON service_access (daily_presence_id, appointment_id)\n    WHERE appointment_id IS NOT NULL;\n\n-- Daily counter used to generate public call codes\nCREATE TABLE IF NOT EXISTS ticket_sequence (\n    ticket_master_id INTEGER NOT NULL REFERENCES ticket_master (id),\n    operational_day  DATE NOT NULL,\n    last_number      INTEGER NOT NULL DEFAULT 0,\n    PRIMARY KEY (ticket_master_id, operational_day)\n);\n-- Append-only history of successful ServiceAccess transitions.\n-- previous_state is NULL for the initial WAITING creation record.\nCREATE TABLE IF NOT EXISTS service_access_transition (\n    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    service_access_id INTEGER NOT NULL REFERENCES service_access (id),\n    previous_state    TEXT\n                          CHECK (previous_state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED')),\n    resulting_state   TEXT NOT NULL\n                          CHECK (resulting_state IN ('WAITING', 'CALLED', 'SUSPENDED', 'ADMITTED')),\n    occurred_at       TIMESTAMP NOT NULL DEFAULT now()\n);\n\n-- Lookups by ServiceAccess, and ordering of recent/latest calls by time\nCREATE INDEX IF NOT EXISTS service_access_transition_access_key\n    ON service_access_transition (service_access_id);\nCREATE INDEX IF NOT EXISTS service_access_transition_order_key\n    ON service_access_transition (occurred_at DESC, id DESC);\n\n-- Recursive location topology: tree or forest, no fixed levels\nCREATE TABLE IF NOT EXISTS location_node (\n    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    parent_id INTEGER REFERENCES location_node (id),\n    label     TEXT NOT NULL\n);\n\n-- Check-in point, belongs to exactly one LocationNode\nCREATE TABLE IF NOT EXISTS totem (\n    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    external_reference TEXT NOT NULL UNIQUE,\n    location_node_id   INTEGER NOT NULL REFERENCES location_node (id)\n);\n\n-- Operational Room, with a unique external reference and a required label\nCREATE TABLE IF NOT EXISTS room (\n    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    room_reference   TEXT NOT NULL UNIQUE,\n    label            TEXT NOT NULL,\n    location_node_id INTEGER NOT NULL REFERENCES location_node (id)\n);\n\n-- At most one workstation per Room, enforced by UNIQUE(room_id)\nCREATE TABLE IF NOT EXISTS room_workstation (\n    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    room_id INTEGER NOT NULL UNIQUE REFERENCES room (id)\n);\n\n-- Zero or one monitor per Room, enforced by UNIQUE(room_id)\nCREATE TABLE IF NOT EXISTS room_monitor (\n    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    room_id INTEGER NOT NULL UNIQUE REFERENCES room (id)\n);\n\n-- Waiting-room display, associated with one or more LocationNodes (its scope)\nCREATE TABLE IF NOT EXISTS waiting_room_monitor (\n    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    label TEXT NOT NULL\n);\n\n-- Scope nodes for a waiting-room display\nCREATE TABLE IF NOT EXISTS waiting_room_monitor_scope (\n    waiting_room_monitor_id INTEGER NOT NULL REFERENCES waiting_room_monitor (id),\n    location_node_id        INTEGER NOT NULL REFERENCES location_node (id),\n    PRIMARY KEY (waiting_room_monitor_id, location_node_id)\n);\n\n-- Check-in origin: the originating Totem, when supplied at check-in\nALTER TABLE daily_presence ADD COLUMN IF NOT EXISTS totem_id\n    INTEGER REFERENCES totem (id);\n\n-- The call-time Room, persisted on a successful call and reused by admission\nALTER TABLE service_access ADD COLUMN IF NOT EXISTS room_id\n    INTEGER REFERENCES room (id);\n"
    )


def downgrade() -> None:
    """Remove the initial AZFlow schema."""
    op.execute(
        """
        DROP TABLE IF EXISTS waiting_room_monitor_scope CASCADE;
        DROP TABLE IF EXISTS waiting_room_monitor CASCADE;
        DROP TABLE IF EXISTS room_monitor CASCADE;
        DROP TABLE IF EXISTS room_workstation CASCADE;
        DROP TABLE IF EXISTS room CASCADE;
        DROP TABLE IF EXISTS totem CASCADE;
        DROP TABLE IF EXISTS location_node CASCADE;
        DROP TABLE IF EXISTS service_access_transition CASCADE;
        DROP TABLE IF EXISTS ticket_sequence CASCADE;
        DROP TABLE IF EXISTS service_access CASCADE;
        DROP TABLE IF EXISTS daily_presence CASCADE;
        DROP TABLE IF EXISTS appointment CASCADE;
        DROP TABLE IF EXISTS queue_agenda CASCADE;
        DROP TABLE IF EXISTS queue CASCADE;
        DROP TABLE IF EXISTS ticket_master CASCADE;
        DROP TABLE IF EXISTS external_agenda CASCADE;
        DROP TABLE IF EXISTS agenda CASCADE;
        DROP TABLE IF EXISTS external_source CASCADE;
        """
    )
